### ISSUE TITLE
Not working with vue 2.2.6

### ISSUE THREAD

**Issue by projct1** [eddyerburgh/vue-digital-clock#1]
http://joxi.ru/KAx58BNI7bqYr8

**Comment by eddyerburgh** [comment]
Hey, sorry about this. 

I copied the .babelrc from another project that use transform-runtime. It's not needed for the clock, so I've removed it.

I've published 1.2.0 to npm. So if you reinstall, it should work fine for you 😄

**Comment by projct1** [comment]
@eddyerburgh Sigh, but still not working 😭 http://joxi.ru/bmoO3EnFBk50my

**Comment by eddyerburgh** [comment]
Are you using babel to transpile?

**Comment by projct1** [comment]
I am using [laraval-mix](https://github.com/JeffreyWay/laravel-mix), and it uses babel surely 😃

**Comment by eddyerburgh** [comment]
Ok thanks, I'll get this fixed for you tonight 👍

**Comment by projct1** [comment]
@eddyerburgh Thanks, i will wait 😊

**Comment by eddyerburgh** [comment]
@rorc I've removed babel from the component and release v1.3.1. This should fix your problem.

I think the problem is that babel is trying to transpile the component in the vue-digital-clock directory. Because there was a .babelrc in the route of the project, it tried to use that. Then it was throwing an error because you did not have the babel plugins installed.

**Comment by projct1** [comment]
@eddyerburgh Yea, thanks dude, now is working 😄
